### ISSUE TITLE
Compile Errors in UIBinderGenerator and UIBinderParser

### ISSUE THREAD

**Issue by roman-e** [ahome-it/ahome-core#6]
Hi

I'm using some of your libraries (ahome-core, ahome-touch, ahome-touch-ux and ahome-sencha-shared). After I updated these libraries and fixed some errors in my code, there remain some last compile errors in the ahome-core library.
The errors occur in the UIBinderGenerator and UIBinderParser classes.
Do I have to include an another library?
These are the errors:

- The constructor UiBinderWriter(JClassType, String, String, TypeOracle, MortalLogger, FieldManager, MessagesWriter, DesignTimeUtils, UiBinderContext, Boolean, boolean, String, ResourceOracle) is undefined
   - UiBinderGenerator.java
   - /lib_touch4j/srcAhomeCore/com/google/gwt/uibinder/rebind
   - line 167
   - Java Problem
- The method getResource(String) is undefined for the type ResourceOracle
   - UiBinderGenerator.java
   - /lib_touch4j/srcAhomeCore/com/google/gwt/uibinder/rebind
   - line 217
   - Java Problem
- StringCase cannot be resolved
   - UiBinderParser.java
   - /lib_touch4j/srcAhomeCore/com/google/gwt/uibinder/rebind
   - line 515
   - Java Problem
- The import com.google.gwt.core.shared.impl.StringCase cannot be resolved
   - UiBinderParser.java
   - /lib_touch4j/srcAhomeCore/com/google/gwt/uibinder/rebind
   - line 26
   - Java Problem
- The method createCssResource(String, String[], JClassType, String, LinkedHashSet<JClassType>) in the type ImplicitClientBundle is not applicable for the arguments (String, String[], JClassType, String, LinkedHashSet<JClassType>, Boolean, ResourceOracle)
   - UiBinderParser.java
   - /lib_touch4j/srcAhomeCore/com/google/gwt/uibinder/rebind
   - line 456
   - Java Problem
- The method createDataResource(String, String) in the type ImplicitClientBundle is not applicable for the arguments (String, String, String, Boolean)
   - UiBinderParser.java
   - /lib_touch4j/srcAhomeCore/com/google/gwt/uibinder/rebind
   - line 191
   - Java Problem

**Comment by eemi2010** [comment]
What version of GWT are you using ? 
Do you use maven or are you using the Touch4j.jar file ?

**Comment by roman-e** [comment]
Hi
Thank you for your reply.
I tried GWT versions 2.5, 2.6 and 2.6.1.
I downloaded the zip files here on github and included the sources into my project.

**Comment by eemi2010** [comment]
Hi, 
currently the lib supports only GWT 2.7 and above. Also make sure that the lib has a higher priority  als the GWT SDK in the classpath.

**Comment by roman-e** [comment]
Great, thank you, now it works. I didn't knew there's already a final build of 2.7, because I always found the RC1.
